version: '3'
services:

  backend:
    build: ./backend
    container_name: backend
    ports:
        - 3000:3000
    
  recommender:
    build: ./recommender
    container_name: recommender
    ports:
        - 3001:3001
    
    
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
        - 8080:8080
    links: 
        - backend
        - recommender